version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: my_docker_app
    
  my_docker_app:
    build: 
      network: host
      context: ./
      dockerfile: Dockerfile
  
    environment:
      - DATABASE_URL=postgresql://postgres:mypass@postgres:5432/my_docker_app

    ports:
      - 8076:8076
    depends_on:
      - postgres